packages:
  - "."
  - "worker"
overrides:
  '@react-pdf/layout': 3.11.5
  restructure: 3.0.0
  '@isaacs/brace-expansion': ^5.0.1
  glob: ^11.1.0
  js-yaml: ^4.1.1
  tar: 7.5.11
  minimatch: ^10.2.3
  markdown-it: ^14.1.1
  ajv: ^8.18.0
  undici: ^6.24.0
  '@tootallnate/once': ^3.0.1
  js-cookie: 3.0.7
  ws: 8.20.1
  picomatch@2.3.1: 2.3.2
  picomatch@4.0.3: 4.0.4
  smol-toml@1.6.0: 1.6.1
  yaml: 2.8.3
  brace-expansion@5.0.2: 5.0.6
allowBuilds:
  '@clerk/shared': false
  '@scarf/scarf': false
  canvas: true
  esbuild: true
  sharp: true
  workerd: true
